<?php

declare(strict_types=1);

namespace Tests\Feature\Public;

use App\Actions\Public\GenerateSitemapAction;
use App\Models\JobListing;
use App\Models\Member;
use App\Models\Organization;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Cache;
use Illuminate\Support\Facades\Queue;
use Tests\TestCase;

/**
 * Phase 8 — sitemap (FR-023). Covers T118 (active-only contents),
 * T119 (listing root present), T120 (well-formed XML).
 *
 * Post-007 follow-up: the route-level behavior switched from a synchronous
 * `GenerateSitemapAction::run()` backstop to a queued dispatch + 503 Retry-After
 * while the file is missing. Tests below verify both the file-present serve
 * path and the file-missing dispatch path, including the cache-lock dedup.
 */
class SitemapTest extends TestCase
{
    use RefreshDatabase;

    private string $path;

    protected function setUp(): void
    {
        parent::setUp();
        // Use a tmp file outside public/ so concurrent test runs don't fight
        // for the canonical artifact and so we never overwrite a real sitemap
        // generated by the dev environment.
        $this->path = tempnam(sys_get_temp_dir(), 'sitemap-test-').'.xml';
        // Reset cache locks between tests so the dispatch-dedup lock doesn't
        // leak state from one test into the next.
        Cache::flush();
    }

    protected function tearDown(): void
    {
        if (is_file($this->path)) {
            @unlink($this->path);
        }
        // The route-level tests pre-generate or assert against the canonical
        // artifact under public/. Clean it up so dev workspaces don't
        // accumulate stale fixture data between runs.
        $canonical = public_path('sitemap.xml');
        if (is_file($canonical)) {
            @unlink($canonical);
        }
        parent::tearDown();
    }

    private function makeOrg(): Organization
    {
        return Organization::factory()->create([
            'member_id' => Member::factory()->create()->id,
            'is_active' => true,
        ]);
    }

    public function test_sitemap_contains_active_offers_only(): void
    {
        $org = $this->makeOrg();

        $active1 = JobListing::factory()->forOrganization($org)->active()->create([
            'title' => 'Coordinador Activo Uno',
            'application_deadline' => now()->addDays(30),
        ]);
        $active2 = JobListing::factory()->forOrganization($org)->active()->create([
            'title' => 'Coordinador Activo Dos',
            'application_deadline' => now()->addDays(30),
        ]);
        $expired = JobListing::factory()->forOrganization($org)->expired()->create([
            'title' => 'Oferta Expirada',
        ]);

        GenerateSitemapAction::run($this->path);

        $xml = (string) file_get_contents($this->path);

        $this->assertStringContainsString('/bolsa-de-trabajo/'.$active1->slug, $xml);
        $this->assertStringContainsString('/bolsa-de-trabajo/'.$active2->slug, $xml);
        $this->assertStringNotContainsString('/bolsa-de-trabajo/'.$expired->slug, $xml);
    }

    public function test_sitemap_includes_listing_root(): void
    {
        $org = $this->makeOrg();
        JobListing::factory()->forOrganization($org)->active()->create([
            'application_deadline' => now()->addDays(30),
        ]);

        GenerateSitemapAction::run($this->path);

        $xml = (string) file_get_contents($this->path);
        $listingRoot = url('/bolsa-de-trabajo');

        $this->assertStringContainsString('<loc>'.$listingRoot.'</loc>', $xml);
    }

    public function test_sitemap_xml_well_formed(): void
    {
        $org = $this->makeOrg();
        JobListing::factory()->forOrganization($org)->active()->create([
            'application_deadline' => now()->addDays(30),
        ]);

        GenerateSitemapAction::run($this->path);

        $xml = (string) file_get_contents($this->path);

        // 1. Parses without warnings.
        $previous = libxml_use_internal_errors(true);
        libxml_clear_errors();
        $doc = simplexml_load_string($xml);
        $errors = libxml_get_errors();
        libxml_clear_errors();
        libxml_use_internal_errors($previous);

        $this->assertNotFalse($doc, 'sitemap.xml must parse as XML.');
        $this->assertEmpty($errors, 'sitemap.xml must parse without libxml errors.');

        // 2. Conforms to the sitemaps.org root element / namespace contract.
        $this->assertSame('urlset', $doc->getName());
        $namespaces = $doc->getDocNamespaces(true);
        $this->assertContains(
            'http://www.sitemaps.org/schemas/sitemap/0.9',
            array_values($namespaces),
            'sitemap.xml must declare the sitemaps.org namespace.'
        );

        // 3. Has at least one <url><loc> child.
        $this->assertGreaterThan(0, count($doc->url));
        $this->assertNotEmpty((string) $doc->url[0]->loc);
    }

    public function test_sitemap_route_serves_xml_when_file_present(): void
    {
        $org = $this->makeOrg();
        JobListing::factory()->forOrganization($org)->active()->create([
            'application_deadline' => now()->addDays(30),
        ]);

        // Pre-generate the canonical artifact since the controller no longer
        // synchronously regenerates as a backstop.
        GenerateSitemapAction::run();

        $response = $this->get('/sitemap.xml');

        $response->assertOk();
        $this->assertStringStartsWith(
            'application/xml',
            (string) $response->headers->get('Content-Type')
        );
        $this->assertStringStartsWith('<?xml', (string) $response->getContent());
    }

    public function test_sitemap_route_returns_503_retry_after_when_file_missing(): void
    {
        Queue::fake();

        // Ensure no canonical artifact exists.
        $canonical = public_path('sitemap.xml');
        if (is_file($canonical)) {
            @unlink($canonical);
        }

        $response = $this->get('/sitemap.xml');

        $response->assertStatus(503);
        $this->assertSame('60', $response->headers->get('Retry-After'));
        $this->assertStringStartsWith('text/plain', (string) $response->headers->get('Content-Type'));
        $this->assertStringContainsString('being generated', (string) $response->getContent());
    }

    public function test_sitemap_route_dispatches_regeneration_job_when_file_missing(): void
    {
        Queue::fake();

        $canonical = public_path('sitemap.xml');
        if (is_file($canonical)) {
            @unlink($canonical);
        }

        $this->get('/sitemap.xml')->assertStatus(503);

        GenerateSitemapAction::assertPushed();
    }

    public function test_sitemap_route_does_not_redispatch_when_dispatch_lock_held(): void
    {
        Queue::fake();

        $canonical = public_path('sitemap.xml');
        if (is_file($canonical)) {
            @unlink($canonical);
        }

        // Simulate a previous request already having acquired the dispatch lock.
        // The new request must still 503 but must NOT queue a duplicate job.
        $lock = Cache::lock('sitemap:dispatch', 600);
        $this->assertTrue($lock->get(), 'precondition: lock acquired by test');

        $this->get('/sitemap.xml')->assertStatus(503);

        GenerateSitemapAction::assertNotPushed();
    }
}
